// Copyright 2023 Brandon Matthews <thenewwazoo@optimaltour.us>
// All rights reserved. GPLv3 License
#pragma once

// Possible values for characteristic CURRENT_DOOR_STATE:
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_OPEN       0
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSED     1
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_OPENING    2
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSING    3
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_STOPPED    4

#define HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_OPEN        0
#define HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_CLOSED      1

#define HOMEKIT_CHARACTERISTIC_CURRENT_LOCK_STATE_UNSECURED  0
#define HOMEKIT_CHARACTERISTIC_CURRENT_LOCK_STATE_SECURED    1
#define HOMEKIT_CHARACTERISTIC_CURRENT_LOCK_STATE_JAMMED     2
#define HOMEKIT_CHARACTERISTIC_CURRENT_LOCK_STATE_UNKNOWN    3

#define HOMEKIT_CHARACTERISTIC_TARGET_LOCK_STATE_UNSECURED   0
#define HOMEKIT_CHARACTERISTIC_TARGET_LOCK_STATE_SECURED     1

#define HOMEKIT_CHARACTERISTIC_OBSTRUCTION_SENSOR_CLEAR      0
#define HOMEKIT_CHARACTERISTIC_OBSTRUCTION_SENSOR_OBSTRUCTED 1

#define HOMEKIT_CHARACTERISTIC_MOTION_NOT_DETECTED 0
#define HOMEKIT_CHARACTERISTIC_MOTION_DETECTED     1

enum GarageDoorCurrentState : uint8_t {
    CURR_OPEN = HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_OPEN,
    CURR_CLOSED = HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSED,
    CURR_OPENING = HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_OPENING,
    CURR_CLOSING = HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSING,
    CURR_STOPPED = HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_STOPPED,
};

enum GarageDoorTargetState : uint8_t {
    TGT_OPEN = HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_OPEN,
    TGT_CLOSED = HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_CLOSED,
};

